apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://your-helm-repo.com
    targetRevision: main
    path: helm/charts/frontend
    helm:
      values: |
        image:
          tag: latest
        canary:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true